"use client";
import { usePathname } from "next/navigation";
import { Menu, X, Plus, Globe2 } from "lucide-react";
import { useEffect, useRef, useState } from "react";
const nav=[["Home","/"],["About","/about"],["Products","/products"],["Services","/services"],["Contact","/contact"]];
export function SiteShell({children}:{children:React.ReactNode}){
 const path=usePathname(),[open,setOpen]=useState(false),root=useRef<HTMLDivElement>(null);
 useEffect(()=>{setOpen(false);const el=root.current;if(!el)return;const reduced=matchMedia("(prefers-reduced-motion: reduce)").matches;const items=el.querySelectorAll(".reveal");const observer=new IntersectionObserver(entries=>entries.forEach(e=>{if(e.isIntersecting){e.target.classList.add("is-visible");observer.unobserve(e.target);}}),{threshold:.08});items.forEach(item=>{if(reduced)item.classList.add("is-visible");else observer.observe(item);});el.classList.add("motion-ready");
 const scroll=()=>{const height=document.documentElement.scrollHeight-innerHeight;el.style.setProperty("--scroll-progress",String(height>0?scrollY/height:0));};scroll();addEventListener("scroll",scroll,{passive:true});
 const click=(event:MouseEvent)=>{const target=(event.target as HTMLElement).closest<HTMLElement>(".btn");if(!target||reduced)return;const box=target.getBoundingClientRect(),ripple=document.createElement("span");ripple.className="click-ripple";ripple.style.left=(event.clientX-box.left)+"px";ripple.style.top=(event.clientY-box.top)+"px";target.appendChild(ripple);setTimeout(()=>ripple.remove(),650);};el.addEventListener("click",click);
 return()=>{observer.disconnect();removeEventListener("scroll",scroll);el.removeEventListener("click",click);};},[path]);
 useEffect(()=>{if(!open)return;const close=(e:KeyboardEvent)=>{if(e.key==="Escape")setOpen(false);};addEventListener("keydown",close);return()=>removeEventListener("keydown",close);},[open]);
 return <div className="site-wrap" ref={root}><a className="skip-link" href="#main-content">Skip to content</a><div className="scroll-progress"/><header className="site-header"><div className="header-inner container"><a href="/" className="brand" aria-label="ANJ Global home"><img src="/anj-global-logo.png" alt="ANJ Global Import and Export"/></a><nav className="desktop-nav" aria-label="Main navigation">{nav.map(([label,href])=><a key={href} href={href} className={path===href?"active":""} aria-current={path===href?"page":undefined}>{label}</a>)}</nav><a href="/contact" className="header-cta">Let’s talk <Plus size={16}/></a><button className="menu-button" aria-label={open?"Close navigation":"Open navigation"} aria-expanded={open} aria-controls="mobile-nav" onClick={()=>setOpen(!open)}>{open?<X/>:<Menu/>}</button></div>{open&&<nav className="mobile-nav" id="mobile-nav" aria-label="Mobile navigation">{nav.map(([label,href],i)=><a href={href} onClick={()=>setOpen(false)} key={href}><span>0{i+1}</span>{label}</a>)}</nav>}</header><main id="main-content">{children}</main><footer className="site-footer"><div className="container footer-grid"><div className="footer-brand"><a href="/" className="brand"><img src="/anj-global-logo.png" alt="ANJ Global Import and Export"/></a><p>Local knowledge.<br/>Global possibilities.</p><span><Globe2 size={15}/> Tamil Nadu, India</span></div><div><h3>Discover</h3>{nav.slice(1).map(([label,href])=><a key={href} href={href}>{label}</a>)}</div><div><h3>We connect</h3><span>Products & markets</span><span>Buyers & suppliers</span><span>Origins & destinations</span><span>Ideas & opportunities</span></div><div><h3>Have a requirement?</h3><p>Make the first connection.</p><a className="footer-email" href="mailto:enquiry@anjglobal.in">enquiry@anjglobal.in</a><a href="/contact" className="text-link">Start a trade enquiry</a></div></div><div className="container footer-bottom"><span>© {new Date().getFullYear()} ANJ Global Import & Export</span><span>Built on connection. Driven by possibility.</span><a href="#main-content">Back to top</a></div></footer></div>;
}
