// Sourcing enquiry categories, not a claim of confirmed stock or supplier availability.
export type ProductGroup = "Agriculture" | "Food & snacks" | "Industry" | "General trade";
export type ProductCategory = {
  name:string; type:ProductGroup; description:string; items:string[];
  image:string; alt:string; packing:string;
};
export const productGroups:ProductGroup[]=["Agriculture","Food & snacks","Industry","General trade"];
export const productCatalog:ProductCategory[]=[
  {name:"Fresh fruits",type:"Agriculture",description:"Seasonal fruit sourcing for wholesale buyers, distributors and food businesses, matched to variety and grade.",items:["Mangoes, bananas & pomegranates","Grapes, papayas & citrus fruit","Coconuts & other seasonal enquiries"],image:"/trade-produce.jpg",alt:"Fresh produce displayed at a market",packing:"Share the variety, size, ripeness, carton weight and delivery date."},
  {name:"Fresh vegetables",type:"Agriculture",description:"Vegetable enquiries for domestic supply and export orders, with handling needs reviewed before dispatch.",items:["Onions, potatoes & tomatoes","Drumsticks, okra & green chillies","Ginger, garlic & leafy vegetables"],image:"/trade-produce.jpg",alt:"Vegetables arranged on a market stall",packing:"Tell us the grade, quantity, packing format and handling requirements."},
  {name:"Rice, grains & millets",type:"Agriculture",description:"Staple grain sourcing for wholesalers, food processors and retail packers, based on your quality specification.",items:["Basmati, non-basmati & parboiled rice","Wheat, maize & other cereal grains","Ragi, pearl millet & foxtail millet"],image:"/product-grains.jpg",alt:"Dry grains and pulses for food sourcing",packing:"Specify the variety, processing preference, bag size and order volume."},
  {name:"Pulses & lentils",type:"Agriculture",description:"Whole and split pulse enquiries for commercial kitchens, processing and wholesale distribution.",items:["Toor dal, urad dal & moong dal","Chickpeas, chana dal & lentils","Whole beans & buyer-specific pulses"],image:"/product-grains.jpg",alt:"A selection of dry grains and pulses",packing:"Include whole or split form, grade, bag weight and destination."},
  {name:"Seeds & oilseeds",type:"Agriculture",description:"Seed sourcing reviewed by variety and intended use, with specifications and required documents agreed first.",items:["Sesame, groundnut & sunflower seed","Vegetable & agricultural seed enquiries","Food, processing or planting requirements"],image:"/product-seeds.jpg",alt:"Seeds shown close up",packing:"State the intended use, variety, test requirements and pack size."},
  {name:"Spices & seasonings",type:"Agriculture",description:"Whole and ground spice enquiries for food manufacturing, wholesale trade and retail packing.",items:["Turmeric, red chilli & coriander","Black pepper, cumin & cardamom","Whole spices & custom blend enquiries"],image:"/product-spices.jpg",alt:"Ground spices and peppercorns on spoons",packing:"Share whole or ground form, grade, quantity and packaging needs."},
  {name:"Chips & crisps",type:"Food & snacks",description:"Crisp snack sourcing for distributors and retailers, with flavour, pack size and shelf-life needs reviewed together.",items:["Potato chips & banana chips","Tapioca chips & regional varieties","Salted, spiced & flavour enquiries"],image:"/product-chips.jpg",alt:"Golden potato chips in a bowl",packing:"Specify flavour, pack weight, carton quantity and required shelf life."},
  {name:"Savoury & traditional snacks",type:"Food & snacks",description:"Regional snack enquiries for food traders and retail supply, guided by recipe, packing and destination needs.",items:["Murukku, mixtures & sev","Roasted gram & spiced peanuts","Regional savoury snack enquiries"],image:"/product-savories.jpg",alt:"Savoury snacks for food sourcing",packing:"Confirm ingredients, allergen information, pack size and shelf life."},
  {name:"Flours & pantry staples",type:"Food & snacks",description:"Dry pantry product enquiries for food service, processing and retail supply in bulk or consumer packs.",items:["Rice flour, wheat flour & gram flour","Millet flour & cooking mix enquiries","Retail packs & wholesale dry goods"],image:"/product-grains.jpg",alt:"Dry food staples including grains and pulses",packing:"Share ingredient specifications, pack format and storage requirements."},
  {name:"Tools & workshop supplies",type:"Industry",description:"Practical sourcing for maintenance teams and workshops, based on size, material and application.",items:["Hand tools & workshop accessories","Cutting tools & abrasives","Maintenance consumable enquiries"],image:"/product-industrial.jpg",alt:"Industrial components and hand tools on a workbench",packing:"Include dimensions, material, intended use and any technical drawings."},
  {name:"Components & machinery spares",type:"Industry",description:"Specification-led enquiries for replacement parts and manufacturing inputs, with compatibility checked before ordering.",items:["Bearings, fasteners & fittings","Mechanical components & fabricated parts","Machinery spare-part enquiries"],image:"/product-industrial.jpg",alt:"A metal mechanical assembly on a workshop table",packing:"Provide part numbers, drawings, tolerances and equipment details."},
  {name:"Packaging & handling materials",type:"Industry",description:"Packing material enquiries to support product protection, consolidation and shipment preparation.",items:["Corrugated cartons & paper packaging","Bags, wrapping & strapping materials","Pallets, crates & protective packing"],image:"/service-warehouse.jpg",alt:"Packed cardboard cartons stacked on warehouse pallets",packing:"Specify dimensions, load capacity, material and printing requirements."},
  {name:"Fabrics & garments",type:"General trade",description:"Textile sourcing enquiries for wholesale, apparel production and commercial buyers, matched to your brief.",items:["Cotton, woven & knitted fabrics","Garments & uniform enquiries","Fabric rolls & buyer-specific colours"],image:"/product-textiles.jpg",alt:"Colourful embroidered fabric rolls",packing:"Share fabric composition, weight, colours, sizes and sample references."},
  {name:"Home textiles & made-ups",type:"General trade",description:"Finished textile enquiries for home, hospitality and retail use, coordinated around material and finish.",items:["Bed linen, pillow covers & towels","Table linen & kitchen textiles","Curtains & other textile made-ups"],image:"/product-textiles.jpg",alt:"Textured fabric rolls in a range of colours",packing:"Confirm dimensions, fabric quality, finishing and individual packing."},
  {name:"General merchandise",type:"General trade",description:"Custom product enquiries for distributors and businesses when a requirement falls outside the listed groups.",items:["Household & kitchenware enquiries","Stationery & commercial supplies","Buyer-specified consumer products"],image:"/service-warehouse.jpg",alt:"Boxed goods in a distribution warehouse",packing:"Send a product reference, material specification, quantity and destination."},
];
